name: hypertrack_pro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Database dependencies - UPDATED to latest stable
  drift: ^2.28.0 # Updated from ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # UI Icons - ADD THIS
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Database code generation - UPDATED to latest stable
  drift_dev: ^2.28.0 # Updated from ^2.20.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
